Swift 3.2 compatibility.
Nike-Inc/Willow pull request #27
Opened 2017-08-10 21:07 UTC by AtomicCat

- Cast value to UInt, as Xcode9b5 compiler appears to default value to an Int and then errors on mixing UInt and Int operations.
- Accept all Xcode9 suggested compiler warning settings.
- Set SWIFT_VERSION to 3.2 in all targets. All targets still build with Swift 3.1/Xcode 8.3.x.
- Rename Network example framework to WebServices to avoid a name collision with an iOS 11 private framework with the same name.

2017-08-14 23:09 UTC, cnoon requested changes
Overall it looks great @AtomicCat! Just a few minor comments and we can get it pushed out.

2017-08-14 23:09 UTC, cnoon commented on CHANGELOG.md
> +- Set SWIFT_VERSION to 3.2 in all targets. All targets still build with Swift 3.1/Xcode 8.3.x.
These should all probably be written in past tense. I'd also probably change the `Fix compile error` to something more like: `Updated source and test code to compile against Swift 3.2 and 4.0.`.

2017-08-14 23:09 UTC, cnoon commented on Example/Frameworks/WebServices/WebServices.h
>  //  Copyright (c) 2015-2016 Nike, Inc. (https://www.nike.com)
Could you bump `2016` to `2017` where applicable?

2017-08-14 23:09 UTC, cnoon commented on Example/iOS Example/ViewController.swift
>  import Willow
Alphabetical?

2017-08-14 23:09 UTC, cnoon commented on Example/iOS Example/WillowConfiguration.swift
>  import Willow
Alphabetical?

2017-08-14 23:09 UTC, cnoon commented on Example/iOS Example/WillowConfiguration.swift
> +        webservicesLogLevels: LogLevel = [.debug, .info, .event],
`webservices` -> `webServices`?

2017-08-14 23:09 UTC, cnoon commented on Source/LoggerConfiguration.swift
> +                let bitValue = UInt(1) << bitShift
👍🏻

2017-08-14 23:09 UTC, cnoon commented on Willow.podspec
> +  s.version = '3.0.1'
I think you might have missed the `Info.plist` and `Info-tvOS.plist` files...

2017-08-14 23:38 UTC, AtomicCat commented on Willow.podspec
> +  s.version = '3.0.1'
fixed

2017-08-14 23:39 UTC, AtomicCat commented on Source/LoggerConfiguration.swift
> +                let bitValue = UInt(1) << bitShift
👍

2017-08-17 14:38 UTC, cnoon approved these changes
Looks good @AtomicCat! 🍻

2017-08-17 14:39 UTC, merged