Update travis to Xcode 9.0
Nike-Inc/Willow pull request #29
Opened 2017-08-23 16:03 UTC by AtomicCat

2017-08-24 16:52 UTC, ejensen approved these changes

2017-08-27 20:17 UTC, cnoon requested changes
A few small comments back to you @AtomicCat.

2017-08-27 20:17 UTC, cnoon commented on .travis.yml
> +    - DESTINATION="OS=11.0,name=iPhone 5S"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
Hmmmm...we should either run tests against the iOS `10.2` or `10.3` simulator instead for the 5S. Then we're getting more coverage for the other platforms.

2017-08-27 20:17 UTC, cnoon commented on CHANGELOG.md
> +  - Added by [Dave Camp](https://github.com/atomiccat) in Pull Request [#27](https://github.com/Nike-Inc/Willow/pull/27).
`Added by` -> `Fixed by`?

2017-08-27 20:17 UTC, cnoon commented on CHANGELOG.md
> +  - Added by [Eric Jensen](https://github.com/ejensen) in Pull Request [#23](https://github.com/Nike-Inc/Willow/pull/23).
`Added by` -> `Fixed by`?

2017-08-27 20:17 UTC, cnoon commented on CHANGELOG.md
> +- Remove redundant cast from Date to Date
`Removed redundant cast` and needs `.` at the end.

2017-08-30 00:34 UTC, cnoon commented
I made the changes called out in my review and pushed them into `master` in commits 47a03d6e and 7d5a547f which keeping your attribution @AtomicCat. 👍🏻

2017-08-30 00:34 UTC, closed without merging